ignore_colors = [
	[0, 0, 0, 0],
	# [0, 0, 0, 255], # filter all black
	[0xff, 0x00, 0xf8, 0xff]
]

version = 16

[priorities]
"0" = 0
"1" = 1
"2" = 5
"3" = 10
"4" = 15

#[[structure]]
#name = "tum"
#file = "images/logo_fish.png"
#startx = 1333
#starty = 763
#priority = 3

[[structure]]
name = "rwth2"
file = "images/rwth+fh-big.png"
startx = 1332
starty = 1172
priority = 3

[[structure]]
name = "hwst"
file = "images/hswt.png"
startx = 1235
starty = 1201
priority = 2

#[[structure]]
#name = "pleadfish"
#file = "images/pleadfish.png"
#startx = 1333
#starty = 753
#priority = 2

#[[structure]]
#name = "fish-background"
#file = "images/fish-background.png"
#startx = 1333
#starty = 753
#priority = 1

#[[structure]]
#name = "augsburg"
#file = "images/augsburg.png"
#startx = 1333
#starty = 753
#priority = 2

#[[structure]]
#name = "slime"
#file = "images/slime.png"
#startx = 1332
#starty = 753
#priority = 2

[[structure]]
name = "logo2"
file = "images/tum_large.png"
startx = 1235
starty = 1172
priority = 3
